### ISSUE TITLE
SAMBRO Homepage 500 Error 

### ISSUE THREAD

**Issue by tewksbg** [sahana/eden#1344]
Error trace 

```
Traceback (most recent call last):
  File "/var/www/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "file stream", line 425, in <module>
  File "/var/www/web2py/gluon/globals.py", line 430, in write
    self.body.write(xmlescape(data))
  File "/var/www/web2py/gluon/html.py", line 131, in xmlescape
    return data.xml()
  File "applications/eden/modules/s3/s3gis.py", line 7098, in xml
    self._setup()
  File "applications/eden/modules/s3/s3gis.py", line 6913, in _setup
    options["feature_resources"] = addFeatureResources(feature_resources)
  File "applications/eden/modules/s3/s3gis.py", line 7515, in addFeatureResources
    url = layer["url"]
KeyError: 'url'
```

**Comment by nursix** [comment]
This happens due to missing map layer configurations - either because they have been deleted or not added to the database in the first place. This configuration error is logged, but no proper compensatory action is taken:
https://github.com/sahana/eden/blob/master/modules/templates/SAMBRO/controllers.py#L51

It would make sense to skip the entire map configuration (i.e. not call show_map at all) rather than just setting layer_id to None, and display a warning message to the user.

**Comment by nursix** [comment]
Probably something for @waidyanatha ("good first issue")
