### ISSUE TITLE
Delphi: Undefined variable during database initialization

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1372]
Database initialization with *Delphi* module enabled fails with
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/shell.py", line 263, in run
    execfile(startfile, _env)
  File "applications/eden/static/scripts/tools/noop.py", line 9, in <module>
    s3db.load_all_models()
  File "applications/eden/modules/s3/s3model.py", line 339, in load_all_models
    cls.load(name)
  File "applications/eden/modules/s3/s3model.py", line 315, in load
    model(name)
  File "applications/eden/modules/s3/s3model.py", line 100, in __init__
    env = self.model()
  File "applications/eden/modules/s3db/delphi.py", line 257, in model
    orderby = table.code,
NameError: global name 'table' is not defined
```

The conflicting method call looks as follows
```python
configure(tablename,
          deduplicate = S3Duplicate(),
          list_fields = ["id",
                         "group_id",
                         "code",
                         "name",
                         "description",
                         "created_by",
                         "modified_on",
                         ],
          orderby = table.code,
          )
```
where the `table` variable is undefined.

Possible solution might be to simply replace the reference with fixed string
```python
          orderby = "code",
```

**Comment by nursix** [comment]
Correct would be:

    orderby = "delphi_problem.code"

**Comment by trendspotter** [comment]
Confirmed. Initialization works now. Thanks.
