### ISSUE TITLE
Can't link incident to asset or facility

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1373]
Steps to reproduce:
1. Create incident in *Events* -> *Incidents*
2. Open the newly created incident (should happen automatically after the creation)
3. Navigate to tab *Assets* or *Facilities*

Following error will occur
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/event.py", line 377, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/event.py", line 176, in incident
    output = s3_rest_controller(rheader = s3db.event_rheader)
  File "/srv/sahana/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 629, in __call__
    pre = preprocess(self)
  File "/srv/sahana/applications/eden/controllers/event.py", line 140, in prep
    f = s3db["event_%s" % cname].event_id
AttributeError: 'Table' object has no attribute 'event_id'
```

**Comment by nursix** [comment]
Fix provided in:
https://github.com/sahana/eden/commit/35d1b3e4c54838fc1f7664ab85d7fdb9904300b2#diff-21a13ac928a047a2dea91a8728413638L139

**Comment by trendspotter** [comment]
Confirmed. Both *Assets* and *Facilities* tabs now display properly. Thanks.
