### ISSUE TITLE
Organisations: unreferenced variable when using settings.org.tags

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1376]
When the `settings.org.tags` configuration directive is enabled, opening an organisation record results in following error
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/org.py", line 481, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/org.py", line 193, in organisation
    return s3db.org_organisation_controller()
  File "applications/eden/modules/s3db/org.py", line 6801, in org_organisation_controller
    rheader = org_rheader,
  File "/srv/sahana/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1787, in __call__
    self._extend_view(output, r, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 2025, in _extend_view
    display = handler(r)
  File "applications/eden/modules/s3db/org.py", line 6370, in org_rheader
    append_tab((T("Tags"), "tag"))
UnboundLocalError: local variable 'append_tab' referenced before assignment
```

Judging from the surrounding lines in *modules/s3db/org.py*, the line
```python
append_tab((T("Tags"), "tag"))
```
should read
```python
tabs.insert(-1, (T("Tags"), "tag"))
```

**Comment by nursix** [comment]
Nah - more like this:
https://github.com/nursix/eden/commit/634531a631b7d3d0510ec95230dcd0b4bbb4ef7d

**Comment by trendspotter** [comment]
Organisation tags work now. Thanks.  
Also, 10,000th commit, congratulations. 🎉

**Comment by nursix** [comment]
Nah - nobody is trying to break records here ;) And it's only 10,000 commits in this repo, but thousands more in previous/other repos (Sahana used to be on Launchpad before), so nothing new really ;)
