### ISSUE TITLE
settings.ui.interim_save breaks CAP Alerts

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1388]
When using CAP module along with `settings.ui.interim_save = True`, *Alerts* die with following traceback
```
Traceback (most recent call last):
  File "/srv/sambro/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sambro/applications/eden/controllers/cap.py", line 1515, in <module>
  File "/srv/sambro/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sambro/applications/eden/controllers/cap.py", line 1032, in alert
    rheader = s3db.cap_rheader,
  File "/srv/sambro/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1774, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 110, in apply_method
    output = self.select(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 1239, in select
    form = self.create(r, **attr).get("form", None)
  File "applications/eden/modules/s3/s3crud.py", line 372, in create
    self._interim_save_button()
  File "applications/eden/modules/s3/s3crud.py", line 3130, in _interim_save_button
    settings.custom_submit.insert(0, item)
AttributeError: 'tuple' object has no attribute 'insert'
```

This is caused by the fact that *Alerts* define their own `custom_submit` which is immutable (a tuple). I see two approaches.

1. Either make the `custom_submit` mutable (list instead of tuple), which I have in [21beef1](https://github.com/trendspotter/eden/commit/21beef16742ca9d53b890547f44da70d8d2b0cdb)
2. Or, since the *Save and edit information* button has pretty much the same functionality as interim save, there can be a check in S3CRUD which determines if the  `custom_submit` is mutable (resp. has *insert* property) and if it's not, it doesn't add the interim save button. This I have in [6523bba](https://github.com/trendspotter/eden/commit/6523bba4d502a16951d83876a58925a5bac4c78d).

Which one would you like to see as PR?

**Comment by nursix** [comment]
Both, sort-of.

For one, cap.py should configure a mutable list, but then also S3CRUD should convert to a list if it isn't a list. Can you do that and send a PR?
