### ISSUE TITLE
Requests filter fails to render (with error 500) when using non-ASCII characters in its translation

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1451]
This is weirdly specific, so I suspect some widget hasn't been yet updated somewhere.

Whenever the [ `Complete` | `None` | `Partial` ] checkbox labels in *Requests* filter on URL `/eden/req/req` are translated using non-ASCII characters, the page fails to load with below stack trace. Interestingly enough, this seems to be the only filter exhibiting the behaviour as we have other filters with checkboxes and labels with diacritics (eg. *Facilities*) which are rendered just fine.

```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/req.py", line 1960, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/req.py", line 104, in req
    output = req_controller()
  File "/srv/web2py/applications/eden/controllers/req.py", line 847, in req_controller
    rheader = s3db.req_rheader,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1778, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 110, in apply_method
    output = self.select(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 1216, in select
    alias = alias
  File "applications/eden/modules/s3/s3filter.py", line 2800, in html
    formstyle=formstyle)
  File "applications/eden/modules/s3/s3filter.py", line 3013, in _render_widgets
    widget = f(resource, get_vars, alias=alias)
  File "applications/eden/modules/s3/s3filter.py", line 223, in __call__
    widget = self.widget(resource, values)
  File "applications/eden/modules/s3/s3filter.py", line 2246, in widget
    widget = w(dummy_field, values, **attr)
  File "applications/eden/modules/s3/s3widgets.py", line 3592, in __call__
    options = self._options(field, value)
  File "applications/eden/modules/s3/s3widgets.py", line 3691, in _options
    for k, v in options if k not in exclude]
  File "/srv/web2py/gluon/html.py", line 1005, in flatten
    s = to_native(c)
  File "/srv/web2py/gluon/_compat.py", line 74, in to_native
    return obj.encode(charset, errors)
  File "/srv/web2py/gluon/languages.py", line 434, in encode
    return str(self).encode(*a, **b)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 0: ordinal not in range(128)
```

**Comment by nursix** [comment]
This should be raised with web2py - to_native(T("Partial", language="ja")) raises an UnicodeDecodeError, but it is rather normal that T's are not ASCII.

I'll work on a workaround.

**Comment by trendspotter** [comment]
If you're positive that it's web2py issue then this might be related - https://github.com/web2py/web2py/issues/1829
(and just for the record, my `import locale; print(locale.getpreferredencoding(False))` prints `ASCII`)

**Comment by nursix** [comment]
Yes, I think this is a web2py issue - https://github.com/web2py/web2py/issues/1856

I don't think it is related to the issue you mentioned, though.

I've published a workaround fix - not very elegant, but it does what's intended and we use this pattern in other places. I left the original code in place in case this gets fixed some time, however.

**Comment by trendspotter** [comment]
Yup, I confirm that https://github.com/nursix/eden/commit/b461b1839c19460bcc9c89c06055365dbf7b7d47 works.

**Comment by trendspotter** [comment]
Reopening. The same issue occurs also in `/eden/deploy/human_resource/1/profile` whenever there is non-ASCII character in the data (eg. when contact's name contains diacritics). The workaround above doesn't help in this case. Traceback is
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/deploy.py", line 981, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/deploy.py", line 160, in human_resource
    output = s3db.hrm_human_resource_controller(extra_filter = q)
  File "applications/eden/modules/s3db/hrm.py", line 7587, in hrm_human_resource_controller
    return current.rest_controller("hrm", "human_resource")
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 629, in __call__
    pre = preprocess(self)
  File "applications/eden/modules/s3db/hrm.py", line 7378, in prep
    name),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2: ordinal not in range(128)
```

**Comment by nursix** [comment]
No, this is not the same issue - it's unrelated.

**Comment by nursix** [comment]
https://github.com/sahana/eden/issues/1456
