### ISSUE TITLE
Event read / update fails with AttributeError (and error 500)

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1453]
Steps to reproduce:
Create an event, filling in just the mandatory values (name, country) is enough.

Expected behavior:
Event is created and can be read / updated.

Actual behavior:
Event is created but read / update operation fails with
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/event.py", line 498, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/event.py", line 89, in event
    return s3_rest_controller(rheader = s3db.event_rheader)
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1791, in __call__
    self._extend_view(output, r, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 2029, in _extend_view
    display = handler(r)
  File "applications/eden/modules/s3db/event.py", line 5635, in event_rheader
    TR(TH("%s: " % table.location_id.label),
AttributeError: 'Table' object has no attribute 'location_id'
```

**Comment by nursix** [comment]
I think that the location_id was accidentally added to the event header during a recent restructuring of the module - but was actually intended to go into the incident header (where it makes sense).

Fix pushed.

**Comment by trendspotter** [comment]
Works. Thanks.
