### ISSUE TITLE
Importing CAP URL feed fails with UnboundLocalError

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1454]
Steps to reproduce:
Import a feed using `/cap/alert/import_feed`

Expected result:
Feed is imported

Actual result:
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/cap.py", line 1532, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/cap.py", line 1024, in alert
    rheader = s3db.cap_rheader,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 688, in __call__
    output = handler(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1778, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3db/cap.py", line 4242, in apply_method
    redirect(URL(c="cap", f="alert", args=[alert_id]))
UnboundLocalError: local variable 'alert_id' referenced before assignment
```

Variable `alert_id` is uninitialized and/or [the condition](https://github.com/sahana/eden/blob/e23b790461a964cfad403af691d9c6bbc33fe975/modules/s3db/cap.py#L4237-L4240) contains just `if`-`elif` but no `else`.

**Comment by nursix** [comment]
@waidyanatha

**Comment by nursix** [comment]
This if-block has multiple problems:
https://github.com/sahana/eden/blob/master/modules/s3db/cap.py#L4237

- setting response.confirmation before redirect makes no sense at all (redirect drops response)
- should not redirect from inside apply_method, but set r.next instead (so that request processing is allowed to complete), and also, with using next, response.confirmation makes sense again
- no, the import is /not/ successful if there is neither import_created nor import_updated, so this must lead to a different response here
- len() is superfluous in both cases

**Comment by biplovbhandari** [comment]
@trendspotter what url are you trying to import?

**Comment by trendspotter** [comment]
For example http://feeds.enviroflash.info/cap/aggregate.xml

**Comment by waidyanatha** [comment]
This is an Atom feed and Eden doesn't have an Atom parser, yet: https://github.com/sahana/SAMBRO/issues/83

I've been labeling such feeds as type = "cms" and not "cap". Then it would parse into the CMS series = "News". Nevertheless, the example you have given doesn't have <link> to pull the CAP data to begin with. Not sure if that's an issue, to be honest. Nevertheless, the type="cms" would parse it to display in the News feed.

Unlike RSS that are quite well defined for carrying CAP message re-directs, the Atom feeds links are inconsistent in providing where the <link> is provided. Sometimes its in the ​in the root <link> tags and sometime its in sub elements <link> tags or even in sub sub element <link> tags. One that the CAP community is toiling with and needs to be standardized.

**Comment by biplovbhandari** [comment]
Actually 'Import CAP URL  Feed' is for single cap source file like [this](http://www.dmhwarning.gov.mm/eden/cap/public/1886.cap)

**Comment by trendspotter** [comment]
Fair enough. Still, failing with error 500 is a bit too punishing. Could it at least fail gracefully with some more user-friendly message?
