### ISSUE TITLE
Organization user roles form render fails with TypeError (and error 500)

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1457]
Steps to reproduce:
1. Configure  
```
settings.auth.entity_role_manager = True
settings.auth.realm_entity_types = ("org_organisation",)
settings.security.policy = 7
```
2. Create an organization
3. Optionally create staff for the organization and define some roles in the administration
4. Navigate to `/eden/org/organisation/1/roles`

Expected result:
Role manager form is rendered

Actual result:
Error 500 and following traceback
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/org.py", line 481, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/org.py", line 193, in organisation
    return s3db.org_organisation_controller()
  File "applications/eden/modules/s3db/org.py", line 6801, in org_organisation_controller
    rheader = org_rheader,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 684, in __call__
    output = handler(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1774, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3aaa.py", line 9019, in apply_method
    context = self.get_context_data(r, **attr)
  File "applications/eden/modules/s3/s3aaa.py", line 9363, in get_context_data
    context = super(S3OrgRoleManager, self).get_context_data(r, **attr)
  File "applications/eden/modules/s3/s3aaa.py", line 9095, in get_context_data
    form = self.get_form()
  File "applications/eden/modules/s3/s3aaa.py", line 9271, in get_form
    fields = self.get_form_fields()
  File "applications/eden/modules/s3/s3aaa.py", line 9447, in get_form_fields
    widget=lambda field, value:
  File "/srv/web2py/gluon/packages/dal/pydal/objects.py", line 1665, in __init__
    self._itype = REGEX_TYPE.match(stype).group(0) if stype else None
TypeError: expected string or buffer
```

When I have pulled an old VM snapshot running on commit https://github.com/sahana/eden/commit/00a7ceed41878e176b97d17725f1184d07f30059, the same configuration worked as expected there (although this remark is probably not very helpful as it's some 300 commits back).

**Comment by nursix** [comment]
https://github.com/nursix/eden/commit/dc3531120af7e44bc9f93c22c6ba40bdd0b66a4b#diff-490b78a7772eee613a7f16277d7ffe14R9463

...should fix it.

The order of keyword arguments in the Field constructor has changed, so that the key-less ```T("User")``` was assigned as field type, but is actually the field label. Using keywords fixes it, and should always have been this way.

Interesting that it ever worked - probably due to a (not-fully-intentional) fallback in PyDAL.

**Comment by trendspotter** [comment]
Works. Thanks.
