### ISSUE TITLE
Volunteers - Service record fails with UnicodeDecodeError when using non-ASCII chars in data

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1458]
Similar case to #1456

Steps to reproduce:
1. Create volunteer, enter information (eg. First name) using non-ASCII character
2. Open volunteer details, click on `Service Record`

Expected result:
PDF is generated

Actual result:
Error 500 with following traceback
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/vol.py", line 546, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/vol.py", line 45, in human_resource
    return s3db.hrm_human_resource_controller()
  File "applications/eden/modules/s3db/hrm.py", line 7621, in hrm_human_resource_controller
    return current.rest_controller("hrm", "human_resource")
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 684, in __call__
    output = handler(self, **attr)
  File "applications/eden/modules/s3db/vol.py", line 1298, in vol_service_record
    pdf_title = vol_name + " - " + s3_unicode(T("Volunteer Service Record")) # %-string substitution doesn't work
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 12: ordinal not in range(128)
```

**Comment by nursix** [comment]
Should be fixed by:

https://github.com/nursix/eden/commit/ade2b35ceb2b101103c89b008507ad15fe53b7ca#diff-ec33d5457de0ea8146d9cfa46a6b2d48L1296

**Comment by trendspotter** [comment]
Works. Thanks.
