### ISSUE TITLE
INV: Shipment receiver representation doesn't handle non-ascii names if telephone contact is set

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1479]
Steps to reproduce:
1. Create an organization
2. Create a facility for the organisation
3. Create a person in person registry. Enter the name using non-ascii characters.
4. Open the person's record and add a mobile phone in contacts.
5. Create a shipment in *Warehouses* -> *Sent Shipments*. Fill in the mandatory values and add the person above as *To person*.
6. Save the shipment and observe the error 500 with below traceback.
7. Navigate back to *Warehouses* -> *Sent Shipments* overview and observe the text in *To Person*.

Expected behaviour:
Shipment is saved without errors + Name and mobile number is displayed in shipments overview.

Actual behaviour:
Error 500 while saving the shipment + ID of the person is displayed instead of the name and mobile number in shipments overview.

Strangely enough, both non-ascii name and telephone needs to be set for this to occur. If neither or only one of the conditions is met, the representation is displayed properly.

```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/inv.py", line 1779, in <module>
  File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/inv.py", line 696, in send
    return s3db.inv_send_controller()
  File "applications/eden/modules/s3db/inv.py", line 2476, in inv_send_controller
    rheader = inv_send_rheader,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 687, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1789, in __call__
    self._extend_view(output, r, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 2027, in _extend_view
    display = handler(r)
  File "applications/eden/modules/s3db/inv.py", line 3955, in inv_send_rheader
    table.recipient_id.represent(record.recipient_id),
  File "applications/eden/modules/s3db/pr.py", line 6619, in pr_person_phone_represent
    s3_phone_represent(row.pr_contact.value),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2: ordinal not in range(128)
```

**Comment by nursix** [comment]
To explain that quickly:

```s3_phone_represent``` was returning a ```unicode```, so combining that with a ```str```, as ```s3_fullname``` returns it, would coerce the combination to ```unicode```.

Consequently, it would try to decode the person's name assuming ASCII-encoding, which fails with a ```UnicodeDecodeError``` if the name contains non-ASCII characters.

No representation function should ever return a ```unicode```, though, as per unicode guideline (5):
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/CodeConventions#Unicode-Guideline

...so encoding ```s3_phone_represent```'s output as utf-8 ```str``` is the fix.

**Comment by trendspotter** [comment]
Works. Thanks.
