### ISSUE TITLE
event module dependency on hrm module

### ISSUE THREAD

**Issue by biplovbhandari** [sahana/eden#1487]
For fresh install using SAMBRO template, gives the event module dependency on hrm module at [this line](https://github.com/sahana/eden/blob/master/modules/s3db/event.py#L3268). The full traceback:
```
Traceback (most recent call last):
  File "/home/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/eden/models/zzz_1st_run.py", line 176, in <module>
    s3db.load_all_models()
  File "applications/eden/modules/s3/s3model.py", line 365, in load_all_models
    cls.load(name)
  File "applications/eden/modules/s3/s3model.py", line 341, in load
    model(name)
  File "applications/eden/modules/s3/s3model.py", line 112, in __init__
    env = self.model()
  File "applications/eden/modules/s3db/event.py", line 3268, in model
    self.req_need_id(empty = False,
  File "applications/eden/modules/s3/s3model.py", line 173, in __getattr__
    AttributeError("undefined table: %s" % name))
  File "applications/eden/modules/s3/s3model.py", line 275, in table
    raise default
AttributeError: undefined table: req_need_id
```

I am not very sure how to remove this dependency. Could you help with this?

**Comment by nursix** [comment]
Hi Biplov--

...this is because the RequestNeedsModel lacks a "defaults" method:
https://github.com/sahana/eden/blob/master/modules/s3db/req.py#L2401

You can add one similar to this:
https://github.com/sahana/eden/blob/master/modules/s3db/dvr.py#L644

...returning req_need_id accordingly.

**Comment by flavour** [comment]
Fixed, sorry
