### ISSUE TITLE
SAMBRO: Internal Server Error in cap/template

### ISSUE THREAD

**Issue by nursix** [sahana/eden#1522]
I have SAMBRO running on a Debian 9 installed using cherokee-postgis script
(.sh) install & config
when I click on menu = Alert --> "Templates" get the error below.

Details - 500, INTERNAL SERVER ERROR

Traceback (most recent call last):
  File "/home/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/eden/compiled/controllers.cap.template.py", line
1563, in <module>
  File "/home/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "applications/eden/compiled/controllers.cap.template.py", line
1300, in template
  File "applications/eden/compiled/models.00_utils.py", line 244, in
s3_rest_controller
  File "applications/eden/modules/s3/s3rest.py", line 621, in __call__
    pre = preprocess(self)
  File "applications/eden/modules/templates/SAMBRO/config.py", line
597, in custom_prep
    result = standard_prep(r)
  File "applications/eden/compiled/controllers.cap.template.py", line
1173, in prep
NameError: global name 'tablename' is not defined

**Comment by nursix** [comment]
Fixed by:
https://github.com/nursix/eden/commit/a1f4a2272c8c2c63b98768ce43b473a91fe1d454

**Comment by nursix** [comment]
Fixed by https://github.com/sahana/eden/commit/a1f4a2272c8c2c63b98768ce43b473a91fe1d454
