### ISSUE TITLE
Several various NoneType errors (setup, vol, project, inv, dc, ...)

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1543]
We're encoutnering a suspiciously high number of failures where a variable of a specific type is expected but it turns out to be `None`. I haven't investigated the possible causes yet, but it almost looks like there may be common cause for them.

All of the following scenarios are done on
 - default template with demo data
 - python 3.8.2
 - Web2py R-2.18.5 (59700b8) with compat patch from eden_deploy

### Scenario 1 - Setup configuration wizard
Steps to reproduce:
1. Log in, go to *Setup* in *Administration* menu
2. Without even changing anything, click on *Submit*.

```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/setup.py", line 776, in <module>
  File "/srv/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/setup.py", line 545, in deployment
    return s3_rest_controller(rheader = s3db.setup_rheader,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 688, in __call__
    output = handler(self, **attr)
  File "/srv/web2py/applications/eden/modules/s3db/setup.py", line 1935, in setup_instance_wizard
    result = setup_modules_apply(r.id, form.vars)
  File "/srv/web2py/applications/eden/modules/s3db/setup.py", line 4671, in setup_modules_apply
    task_vars["instance_id"] = instance_id # To Upload Logs to Instance record
TypeError: 'NoneType' object does not support item assignment
```

### Scenario 2 - Volunteer service record
Steps to reproduce:
1. Log in, create organization if none exists yet
2. Go to *Volunteers* -> *Course Catalog* -> *Create*
3. Create a new course, fill in mandatory fields (name) and *Save*
4. Go to *Volunteers* -> *Volunteers* -> *Create*
5. Fill in the mandatory fields (org, name) and *Save*
6. Go to *Trainings* tab, add training created in step 3 and *Save*
7. Click on volunteer's *Service Record*

```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/vol.py", line 527, in <module>
  File "/srv/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/vol.py", line 46, in human_resource
    return s3db.hrm_human_resource_controller()
  File "/srv/web2py/applications/eden/modules/s3db/hrm.py", line 8288, in hrm_human_resource_controller
    return current.rest_controller("hrm", "human_resource")
  File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 688, in __call__
    output = handler(self, **attr)
  File "/srv/web2py/applications/eden/modules/s3db/vol.py", line 1297, in vol_service_record
    return exporter(r.resource,
  File "/srv/web2py/applications/eden/modules/s3/s3export.py", line 220, in pdf
    return codec(*args, **kwargs)
  File "/srv/web2py/applications/eden/modules/s3/codecs/pdf.py", line 303, in encode
    body_flowable = self.get_html_flowable(callback(r),
  File "/srv/web2py/applications/eden/modules/s3db/vol.py", line 1120, in callback
    hours[_date.date()] = {"course": row["hrm_course"].name,
AttributeError: 'NoneType' object has no attribute 'date'
```

### Scenario 3 - Project summary report
Steps to reproduce:
1. Log in, create organization if none exists yet
2. Go to *Projects* -> *Projects* -> *Create*
3. Create a new project, fill in mandatory fields (org, name) and *Save*
4. Open the project, go to *Indicators* tab
5. Create a new indicator, fill in code and *Save*
6. Click on *Project summary report*, then *Generate PDF*

```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/project.py", line 1492, in <module>
  File "/srv/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/project.py", line 492, in project
    return s3_rest_controller(module, "project",
  File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 688, in __call__
    output = handler(self, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 1775, in __call__
    output = self.apply_method(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3db/project.py", line 7139, in apply_method
    output = self.pdf(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3db/project.py", line 8346, in pdf
    project, goals = self._extract(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3db/project.py", line 7347, in _extract
    goals[goal_id]["outcomes"][outcome_id]["outputs"][output_id]["indicators"][indicator_id] = {"code" : row.code,
KeyError: None
```

### Scenario 4 - Warehouse reports
Steps to reproduce:
1. Log in
2. Go to *Warehouses* -> *Warehouses* -> *Create*
3. Create a new warehouse, fill in mandatory fields (name) and *Save*
4. Go to *Warehouses* -> *Received/Incoming shipments* -> *Create*
5. Create a new shipment, fill in mandatory fields (warehouse, type) and *Save*
6. Click *Add item to shipment*
7. Add item to shipment, fill in mandatory fields (item - e.g. ventilator, qty) and *Save*
8. Click on *Report* -> *Utilization report*

```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/inv.py", line 1785, in <module>
  File "/srv/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/inv.py", line 1498, in track_item
    output = s3_rest_controller(rheader = s3db.inv_rheader,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 1775, in __call__
    output = self.apply_method(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3crud.py", line 113, in apply_method
    output = self.select(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3crud.py", line 1204, in select
    output = self._datatable(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3crud.py", line 1517, in _datatable
    dt, totalrows = resource.datatable(fields = list_fields,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 924, in datatable
    data = self.select(selectors,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 516, in select
    data = S3ResourceData(self,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 5749, in __init__
    records = self.extract(rows,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 6344, in extract
    value = value()
  File "/srv/web2py/gluon/packages/dal/pydal/objects.py", line 2554, in __call__
    return self.method(self.row, *args, **kwargs)
  File "/srv/web2py/applications/eden/modules/s3db/inv.py", line 1951, in inv_track_item_total_value
    v = row.quantity * row.pack_value
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

There are several more scenarios which fail in similar fashion (NoneType related) for which we didn't test the minimal steps to reproduce yet, as there may be common fix for them all.

E.g. Assessment response creation in dc module fails with
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/dc.py", line 200, in <module>
  File "/srv/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/dc.py", line 194, in respnse
    return s3_rest_controller("dc", "response",
  File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 629, in __call__
    pre = preprocess(self)
  File "/srv/web2py/applications/eden/controllers/dc.py", line 189, in prep
    s3db.dc_answer_form(r, tablename)
  File "/srv/web2py/applications/eden/modules/s3db/dc.py", line 1402, in dc_answer_form
    for posn in layout:
TypeError: 'NoneType' object is not iterable
```
and so on...

If they don't have common cause and you'd like to have a separate issues for them, I'd be happy to split them.

**Comment by nursix** [comment]
In all of these cases, it seems, a query result Row contains a field value None where it should not, i.e. the Row encountered is invalid.

One possible scenario is a broken database that contains invalid records - due to either a write error (broken PyDAL?), or a botched migration, or some external manipulation. It should be easy to check the records in question - although it may be harder to find out how they got into the database.

If the records are valid (i.e. do not contain None where the query delivers None), then it could be that you're running a broken PyDAL version. Did you, after resetting to web2py-2.18.5-stable, also do a `git submodule update --recursive`?

If PyDAL is of the correct version, but the query does however deliver invalid results, this could still be a bug in PyDAL (compatibility issue with Python-3.8). Or, it could be that the DB driver version you use is incompatible or broken.

Which of the above can you confirm?

**Comment by nursix** [comment]
Hmm, on the other hand - I can reproduce the issues in an otherwise working system, so it does not seem that a DB or DAL issue is behind them.

Looking at the code, they do not appear to have a common cause - although they kinda follow a common pattern.

It seems that in the majority of these cases, None (i.e. no input) is actually accepted by the respective form, no default is set for the field, and yet the analyzing code does not check for resp. exclude None.

So that's simply bugs.

I would say it is not necessary to split the issues reported above - but if you have more to report, it may be helpful if you reported them individually, or at least separate per module.

**Comment by nursix** [comment]
...because even if they follow a common pattern, they may require entirely different resolutions.

For some of them, making the field mandatory may be correct, for others, it is better to have the analyzing code check for None (or exclude None), and for yet others, a default value may be in order. At least one of the above needs a case discrimination because None means something.

**Comment by nursix** [comment]
As a side note for developers (=note to myself): none of the functions tested here with the default template was actually developed in the context of the default template. The templates that originally used them did not allow None to occur in the respective fields.

In other words: these are context regression issues, i.e. whilst they do not have a common cause in the code, they do have a common cause in the development process. It is possible to prevent this by re-instating the policy to not expose functionality by default unless it has been tested in the context of the default template.

**Comment by trendspotter** [comment]
Strange that we didn't see these errors in previous testing iterations few months ago. A problem in our database stack is not that unbelievable, because we're using fairly cutting-edge versions and already had some problems in another application with psycopg vs. Postgres 12 compatibility. That would also explain another problem we're having with `psycopg2.errors.InFailedSqlTransaction` during direct database access via web2py admin panel (different testing instance, unrelated to the errors reported above) which we also haven't explored further yet.

However the stack traces in the scenarios above vary wildly and in most places it's consistent with the actual input. E.g. no wonder that `row.quantity * row.pack_value` fails when pack_value hasn't been given and is NULL in database, so it eventually makes sense that we've just lucked out and found a bunch of similar-looking problems. If we find more, I'll report them separately (or maybe even attempt to fix, if that'll be obvious enough even for me).

As for the original question, yes, we're running `git submodule update --recursive` after checking out the recommended web2py version/commit.

**Comment by nursix** [comment]
Hmm - if you are running the exact same test cases now as you did a few months ago, then you should have found these issues already a few months ago, since the code in question is not that new.

So I would say your testing has become a tad more destructive this time - which is a good thing, and very welcome, because this type of issues can only be found by destructive (or call it "naive") testing. 

Never mind the terminology, it doesn't mean there's something wrong with the way you are testing. It rather means: developer testing is always biased, especially when development happens in the context of a custom template, and may thus not find such problems.

We used to have some level of peer review, but this has become more and more superficial and now completely suspended because as powerful and effective as it can be, nobody wants to be that watchdog constantly breathing down the other developer's necks - it's a rather unpopular position. As a result, of course, more of these issues may slip through, and so we rely on people like you to report them, many thanks.

**Comment by flavour** [comment]
Thanks for giving such clear steps to reproduce, along with the tracebacks...makes resolving them much easier :)

> ### Scenario 1 - Setup configuration wizard

I believe this is because PyYAML ins't installed?
So this should at least prevent the crash (although obviously the system won't work!)
https://github.com/sahana/eden/commit/69ea576e662b34c5cbf94c919a564ddb492538a8

> ### Scenario 2 - Volunteer service record
> AttributeError: 'NoneType' object has no attribute 'date'

Dominic has fixed this issue with the Service Record crashing when there are undated Trainings in the user profile (which is a perfectly possible scenario as we should cope with partial data):
https://github.com/sahana/eden/commit/ac42c15c10f59451053f7532bf5d6ed14f22ed7a

> ### Scenario 3 - Project summary report

I am looking at this next

> ### Scenario 4 - Warehouse reports
>     v = row.quantity * row.pack_value
> TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Dominic has fixed this issue where the Pack Value hasn't been defined (which again is fine...we should cope with partial data):
https://github.com/sahana/eden/commit/75b4c66f2d304f1762a48171811bff1a21ac6f0c

> E.g. Assessment response creation in dc module fails with

After the Projects, I'll have a pass at making DC work better in Default (although, as per #1545, this is unlikely to be a usable out-of-the box solution until the UCCE editor is backported)

**Comment by flavour** [comment]
> ### Scenario 3 - Project summary report

Fixed here: https://github.com/sahana/eden/commit/23b26785f3ea594a73e738cbfc7535a749eb3ef3

This one was an example of stuff which was developed for a Template which needs more available for Default: in this case I decided to enable Indicators for Projects in default, as this is such a common aspect of projects, but didn't want to enable all of the associated Goals/Outcomes/Outputs which are needed for these Reports...Projects already have way too many tabs by default...this can be reviewed, of course...but for now at least no unexpected crashes by trying to run reports which can't run

**Comment by trendspotter** [comment]
Thank you. All 4 scenarios above now seem to work as expected (i.e. without crashes :) ).

> but for now at least no unexpected crashes

Yes, this is kinda what we're aiming for. The app should try its best to either work with missing data or fail gracefully. Knowing that "*it works in the default*" helps us tremendously whenever we attempt to customize any part and fail miserably.

**Comment by flavour** [comment]
Fix for the DC part:
https://github.com/sahana/eden/commit/81d40dcbb67da2176cacd4341a7de2c75310c0a5
