### ISSUE TITLE
CMS: Enabling and managing comments causes NameError loop

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1550]
Steps to reproduce:
1. Log in and navigate to *Administration* -> *CMS*
2. Open a post (any from the default 3)
3. Check *Comments permitted?* and click *Save*
4. Click on *Comments* tab
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/cms.py", line 973, in <module>
  File "/srv/web2py/gluon/globals.py", line 429, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/cms.py", line 858, in comments
    form = crud.create(table)
NameError: name 'crud' is not defined
```
There seems to be some javascript periodically refreshing the content which leads to the error ticket being created in loop until the user closes the tab or navigates elsewhere.

**Comment by flavour** [comment]
https://github.com/sahana/eden/commit/c5cbc49c5bda875a0159151f21622269b80ac50e#diff-6a00368471a6b130e64676c17d53451fR856
