### ISSUE TITLE
Attempt to import invalid organization logo fails with ValueError

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1554]
Steps to reproduce:
1. Go to *Organizations* -> *Import*
2. Attempt to import organization with logo using URL without protocol - [organizations.txt](https://github.com/sahana/eden/files/4532604/organizations.txt) (rename to *.csv)
3. Clicking on *Submit* fails with
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/org.py", line 511, in <module>
  File "/srv/web2py/gluon/globals.py", line 429, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/org.py", line 175, in organisation
    return s3db.org_organisation_controller()
  File "/srv/web2py/applications/eden/modules/s3db/org.py", line 6877, in org_organisation_controller
    output = current.rest_controller("org", "organisation",
  File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 688, in __call__
    output = handler(self, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 1775, in __call__
    output = self.apply_method(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 274, in apply_method
    output = self.generate_job(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 405, in generate_job
    self._generate_import_job(upload_id,
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 1004, in _generate_import_job
    resource.import_xml(src,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 2483, in import_xml
    success = self.import_tree(id, tree,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 2712, in import_tree
    success = add_item(element = element,
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 3142, in add_item
    if not item.parse(element,
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 1832, in parse
    data = xml.record(table, element,
  File "/srv/web2py/applications/eden/modules/s3/s3xml.py", line 1559, in record
    upload = urlopen(download_url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'example.com/logo.png'
```

Expected outcome: Either attempt to resolve the value by prepending a protocol or display standard validation error in the import job details.

Moreover, we have noticed that there are fields which can't be imported as they are completely missing from the XSL in some imports - e.g. Organization's *Year* - is this expected?

**Comment by flavour** [comment]
> Moreover, we have noticed that there are fields which can't be imported as they are completely missing from the XSL in some imports - e.g. Organization's _Year_ - is this expected?

Expected yes, since this is a RAD platform that evolves as-required...if no-one needs that in the import XSL then it isn't added there....until it does get needed.
Patches definitely accepted to resolve these.

F

**Comment by flavour** [comment]
> Either attempt to resolve the value by prepending a protocol or display standard validation error in the import job details.

I'm not sure we should prepend the protocol since we have no easy way of knowing this is a URL as opposed to a file_path...but yes it definitely shouldn't crash!

**Comment by trendspotter** [comment]
> we have no easy way of knowing this is a URL as opposed to a file_path

`example.com/logo.png` already is a file path, albeit relative. However with absolute path it fails the same. So it looks like a protocol is needed anyway (`file://` protocol in this case).
