### ISSUE TITLE
Volunteer creation fails with AttributeError: 'Table' object has no attribute 'missing'

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1583]
**Steps to reproduce:**
1. Install fresh Sahana Eden git master ([2787edb](https://github.com/sahana/eden/commit/2787edbf27dac9eac12bf6aff32522b7c0af1397)) with _default_ template with no additional changes.
2. Create organization.
3. Fill in volunteer creation form `/eden/vol/volunteer/create`.
4. Click _Save_.

**Expected result:**
Volunteer is created without errors.

**Actual result:**
Volunteer record is created, but the following error is emitted in the process:

```pytb
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/vol.py", line 568, in <module>
  File "/srv/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/vol.py", line 52, in person
    return vol_person_controller()
  File "/srv/web2py/applications/eden/modules/s3db/vol.py", line 1886, in vol_person_controller
    return current.rest_controller("pr", resourcename,
  File "/srv/web2py/applications/eden/models/00_utils.py", line 268, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 662, in __call__
    pre = preprocess(self)
  File "/srv/web2py/applications/eden/modules/s3db/vol.py", line 1684, in prep
    table.missing.readable = table.missing.writable = False
AttributeError: 'Table' object has no attribute 'missing'
```

**Comment by flavour** [comment]
Thanks!
