### ISSUE TITLE
Med: Hospital import fails with AttributeError: 'DAL' object has no attribute 'org_organisation_organisation_type'

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1586]
**Steps to reproduce:**

1. Install fresh Sahana Eden git master ([06fced6](https://github.com/sahana/eden/commit/06fced6de6e11a3244ff27ba5e59fe69d87af603)) with default template.
2. Enable "med" (Hospitals) module in `config.py` before the first run.
3. Start the instance, log in, and navigate to `/eden/med/hospital/import`.
4. Import CSV file [hospital.csv](https://github.com/sahana/eden/files/8317452/hospital.csv).
5. Click on "Import" after validation.

**Expected result:**
Hospital is created along with the necessary records on which it depends.
OR
The attempt to import fails validation with human readable message if the records on which it depend are required to exist beforehand.

**Actual result:**
Import fails with the following stack trace:

```pytb
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/eden/controllers/med.py", line 384, in <module>
  File "/srv/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/applications/eden/controllers/med.py", line 344, in hospital
    return s3_rest_controller(rheader = med_hospital_rheader)
  File "/srv/web2py/applications/eden/models/00_utils.py", line 268, in s3_rest_controller
    output = r(**attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 721, in __call__
    output = handler(self, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 1877, in __call__
    output = self.apply_method(r, **attr)
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 287, in apply_method
    return self.commit_items(upload_id, items)
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 627, in commit_items
    self._commit_import_job(upload_id, items)
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 1197, in _commit_import_job
    resource.import_xml(None,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 1757, in import_xml
    success = self.import_tree(id, tree,
  File "/srv/web2py/applications/eden/modules/s3/s3resource.py", line 2005, in import_tree
    success = import_job.commit(ignore_errors = ignore_errors,
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 3769, in commit
    success = item.commit(ignore_errors=ignore_errors)
  File "/srv/web2py/applications/eden/modules/s3/s3import.py", line 2677, in commit
    callback(onaccept, form) # , tablename=tablename (if we ever define callbacks as a dict with tablename)
  File "/srv/web2py/gluon/tools.py", line 81, in callback
    [action(form) for action in actions]
  File "/srv/web2py/gluon/tools.py", line 81, in <listcomp>
    [action(form) for action in actions]
  File "/srv/web2py/applications/eden/modules/s3db/org.py", line 995, in org_branch_onaccept
    ltable = db.org_organisation_organisation_type
  File "/srv/web2py/gluon/packages/dal/pydal/base.py", line 790, in __getattr__
    return BasicStorage.__getattribute__(self, key)
AttributeError: 'DAL' object has no attribute 'org_organisation_organisation_type'
```

**Comment by flavour** [comment]
Thanks!
